# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtMultimediaWidgets import QVideoWidget

from PyQt5.QtMultimedia import QMediaPlayer

class trialPlaybackSubWindowWidget(QtWidgets.QWidget):
    def __init__(self, parent=None):
        print('Initialize parent widget')
        super(trialPlaybackSubWindowWidget, self).__init__()

    def build_playback_window(self):
        print('Initialize actual widget')
        #self.trialPlaybackSubWindowWidget = QtWidgets.QWidget()
        # self.trialPlaybackSubWindowWidget.setObjectName("trialPlaybackSubWindowWidget")  # set in main_window_ui.py

        self.mediaPlayer =  QMediaPlayer(None, QMediaPlayer.VideoSurface)    
        videoWidget = QVideoWidget()
        self.mediaPlayer.setVideoOutput(videoWidget)
        self.playLastTrial_Button = QtWidgets.QPushButton(self)
        self.playLastTrial_Button.setGeometry(QtCore.QRect(90, 180, 75, 23))
        self.playLastTrial_Button.setObjectName("playLastTrial_Button")
        self.playLastTrial_Button.setIcon(self.style().standardIcon(QtWidgets.QStyle.SP_MediaPlay))

        self.positionSlider = QtWidgets.QSlider(QtCore.Qt.Horizontal)
        self.positionSlider.setRange(0, 0)
        self.positionSlider.setGeometry(QtCore.QRect(100, 170, 10, 30))

        # Create layouts to place inside widget
        controlLayout = QtWidgets.QHBoxLayout()
        controlLayout.setContentsMargins(0, 0, 0, 0)
        controlLayout.addWidget(self.playLastTrial_Button)
        controlLayout.addWidget(self.positionSlider)

        layout = QtWidgets.QVBoxLayout()
        layout.addWidget(videoWidget)
        layout.addLayout(controlLayout)

        self.setLayout(layout)
        print('Initialized subwindow widget')