# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odor_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1104, 755)
        self.odorSaveButton = QtWidgets.QPushButton(Dialog)
        self.odorSaveButton.setGeometry(QtCore.QRect(810, 720, 75, 23))
        self.odorSaveButton.setObjectName("odorSaveButton")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 120, 651, 501))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.odorLoadButton = QtWidgets.QPushButton(Dialog)
        self.odorLoadButton.setGeometry(QtCore.QRect(730, 720, 75, 23))
        self.odorLoadButton.setObjectName("odorLoadButton")
        self.odorSaveasButton = QtWidgets.QPushButton(Dialog)
        self.odorSaveasButton.setGeometry(QtCore.QRect(890, 720, 75, 23))
        self.odorSaveasButton.setObjectName("odorSaveasButton")
        self.generateOdorTableButton = QtWidgets.QPushButton(Dialog)
        self.generateOdorTableButton.setGeometry(QtCore.QRect(490, 650, 161, 23))
        self.generateOdorTableButton.setAutoDefault(False)
        self.generateOdorTableButton.setObjectName("generateOdorTableButton")
        self.stimuliTable = QtWidgets.QTableWidget(Dialog)
        self.stimuliTable.setGeometry(QtCore.QRect(680, 120, 421, 501))
        self.stimuliTable.setObjectName("stimuliTable")
        self.stimuliTable.setColumnCount(4)
        self.stimuliTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.stimuliTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuliTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuliTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stimuliTable.setHorizontalHeaderItem(3, item)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.odorSaveButton.setText(_translate("Dialog", "Save"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Vial number"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Odor"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "% Headspace"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "MFC"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Dilutor"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Repetitions num"))
        self.odorLoadButton.setText(_translate("Dialog", "Load"))
        self.odorSaveasButton.setText(_translate("Dialog", "Save as..."))
        self.generateOdorTableButton.setText(_translate("Dialog", "Generate stimuli table"))
        item = self.stimuliTable.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Vial"))
        item = self.stimuliTable.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Odor"))
        item = self.stimuliTable.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "MFC"))
        item = self.stimuliTable.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Dilutor"))
