# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odor_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1104, 755)
        self.saveStimuliListFile = QtWidgets.QPushButton(Dialog)
        self.saveStimuliListFile.setGeometry(QtCore.QRect(940, 630, 75, 23))
        self.saveStimuliListFile.setObjectName("saveStimuliListFile")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 120, 651, 501))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.loadStimuliListFile = QtWidgets.QPushButton(Dialog)
        self.loadStimuliListFile.setGeometry(QtCore.QRect(860, 630, 75, 23))
        self.loadStimuliListFile.setObjectName("loadStimuliListFile")
        self.saveAsStimuliListFile = QtWidgets.QPushButton(Dialog)
        self.saveAsStimuliListFile.setGeometry(QtCore.QRect(1020, 630, 75, 23))
        self.saveAsStimuliListFile.setObjectName("saveAsStimuliListFile")
        self.generateOdorTableButton = QtWidgets.QPushButton(Dialog)
        self.generateOdorTableButton.setGeometry(QtCore.QRect(690, 630, 161, 23))
        self.generateOdorTableButton.setAutoDefault(False)
        self.generateOdorTableButton.setObjectName("generateOdorTableButton")
        self.stimuliTable = QtWidgets.QTableWidget(Dialog)
        self.stimuliTable.setGeometry(QtCore.QRect(680, 120, 421, 501))
        self.stimuliTable.setObjectName("stimuliTable")
        self.stimuliTable.setColumnCount(0)
        self.stimuliTable.setRowCount(0)
        self.saveStimuliConfigFile = QtWidgets.QPushButton(Dialog)
        self.saveStimuliConfigFile.setGeometry(QtCore.QRect(500, 630, 75, 23))
        self.saveStimuliConfigFile.setObjectName("saveStimuliConfigFile")
        self.loadStimuliConfigFile = QtWidgets.QPushButton(Dialog)
        self.loadStimuliConfigFile.setGeometry(QtCore.QRect(420, 630, 75, 23))
        self.loadStimuliConfigFile.setObjectName("loadStimuliConfigFile")
        self.saveAsStimuliConfigFile = QtWidgets.QPushButton(Dialog)
        self.saveAsStimuliConfigFile.setGeometry(QtCore.QRect(580, 630, 75, 23))
        self.saveAsStimuliConfigFile.setObjectName("saveAsStimuliConfigFile")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.saveStimuliListFile.setText(_translate("Dialog", "Save"))
        self.loadStimuliListFile.setText(_translate("Dialog", "Load"))
        self.saveAsStimuliListFile.setText(_translate("Dialog", "Save as..."))
        self.generateOdorTableButton.setText(_translate("Dialog", "Generate stimuli table"))
        self.saveStimuliConfigFile.setText(_translate("Dialog", "Save"))
        self.loadStimuliConfigFile.setText(_translate("Dialog", "Load"))
        self.saveAsStimuliConfigFile.setText(_translate("Dialog", "Save as..."))
