# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'odor_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1104, 755)
        self.saveOdorTableButton = QtWidgets.QPushButton(Dialog)
        self.saveOdorTableButton.setGeometry(QtCore.QRect(810, 720, 75, 23))
        self.saveOdorTableButton.setObjectName("saveOdorTableButton")
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 120, 651, 501))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.odorLoadButton = QtWidgets.QPushButton(Dialog)
        self.odorLoadButton.setGeometry(QtCore.QRect(730, 720, 75, 23))
        self.odorLoadButton.setObjectName("odorLoadButton")
        self.saveOdorTableAsFileButton = QtWidgets.QPushButton(Dialog)
        self.saveOdorTableAsFileButton.setGeometry(QtCore.QRect(890, 720, 75, 23))
        self.saveOdorTableAsFileButton.setObjectName("saveOdorTableAsFileButton")
        self.generateOdorTableButton = QtWidgets.QPushButton(Dialog)
        self.generateOdorTableButton.setGeometry(QtCore.QRect(490, 650, 161, 23))
        self.generateOdorTableButton.setAutoDefault(False)
        self.generateOdorTableButton.setObjectName("generateOdorTableButton")
        self.stimuliTable = QtWidgets.QTableWidget(Dialog)
        self.stimuliTable.setGeometry(QtCore.QRect(680, 120, 421, 501))
        self.stimuliTable.setObjectName("stimuliTable")
        self.stimuliTable.setColumnCount(0)
        self.stimuliTable.setRowCount(0)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.saveOdorTableButton.setText(_translate("Dialog", "Save"))
        self.odorLoadButton.setText(_translate("Dialog", "Load"))
        self.saveOdorTableAsFileButton.setText(_translate("Dialog", "Save as..."))
        self.generateOdorTableButton.setText(_translate("Dialog", "Generate stimuli table"))
