# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sound_config.ui'
#
# Created by: PyQt5 UI code generator 5.15.8
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1104, 755)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(10, 120, 651, 501))
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.AllEditTriggers)
        self.tableWidget.setRowCount(0)
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setObjectName("tableWidget")
        self.saveSoundConfigFile = QtWidgets.QPushButton(Dialog)
        self.saveSoundConfigFile.setGeometry(QtCore.QRect(500, 630, 75, 23))
        self.saveSoundConfigFile.setObjectName("saveSoundConfigFile")
        self.loadSoundConfigFile = QtWidgets.QPushButton(Dialog)
        self.loadSoundConfigFile.setGeometry(QtCore.QRect(420, 630, 75, 23))
        self.loadSoundConfigFile.setObjectName("loadSoundConfigFile")
        self.saveAsSoundConfigFile = QtWidgets.QPushButton(Dialog)
        self.saveAsSoundConfigFile.setGeometry(QtCore.QRect(580, 630, 75, 23))
        self.saveAsSoundConfigFile.setObjectName("saveAsSoundConfigFile")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.saveSoundConfigFile.setText(_translate("Dialog", "Save"))
        self.loadSoundConfigFile.setText(_translate("Dialog", "Load"))
        self.saveAsSoundConfigFile.setText(_translate("Dialog", "Save as..."))
